id = "comment-block-snippets"
name = "Comment Blocks "
version = "1.0.2"
schema_version = 1
authors = ["Rami Shalhoub <rami2002.work@gmail.com>"]
description = "sippets to add comment blocks"
repository = "https://github.com/rami-shalhoub/comment-blocks-zed"
snippets = [
   "./snippets/dash_style/haskell.json",
   "./snippets/dash_style/lua.json",
   "./snippets/dash_style/sql.json",
   "./snippets/hashtag_style/perl.json",
   "./snippets/hashtag_style/python.json",
   "./snippets/hashtag_style/r.json",
   "./snippets/hashtag_style/ruby.json",
   "./snippets/hashtag_style/shell script.json",
   "./snippets/hashtag_style/yaml.json",
   "./snippets/slash_style/c.json",
   "./snippets/slash_style/c++.json",
   "./snippets/slash_style/csharp.json",
   "./snippets/slash_style/dart.json",
   "./snippets/slash_style/go.json",
   "./snippets/slash_style/java.json",
   "./snippets/slash_style/javascript.json",
   "./snippets/slash_style/kotlin.json",
   "./snippets/slash_style/php.json",
   "./snippets/slash_style/rust.json",
   "./snippets/slash_style/swift.json",
   "./snippets/slash_style/typescript.json",
   "./snippets/slash_style/tsx.json",
   "./snippets/css.json",
   "./snippets/html.json",
   "./snippets/prolog.json"
]
